@startuml
!$index = 0

object "__:ArmInitialized__" as arm {
  !$index = $index + 1
  sequence_index = $index
  position = 1
  is_loaded = false
  is_clean = false
  is_lowered = false
}

object "__:TipsInstalled__" as tips {
  !$index = $index + 1
  sequence_index = $index
  position = 20
}

object "__:WasteInstalled__" as waste {
  !$index = $index + 1
  sequence_index = $index
  position = 30
}

object "__:ReservoirAdded__" as water {
  !$index = $index + 1
  sequence_index = $index
  position = 1
  description = "water"
}

object "__:ReservoirAdded__" as glucose {
  !$index = $index + 1
  sequence_index = $index
  position = 2
  description = "glucose solution"
}

object "__:ReservoirAdded__" as phosphate {
  !$index = $index + 1
  sequence_index = $index
  position = 3
  description = "phosphate buffer"
}

object "__:TargetPlateAdded__" as target {
  !$index = $index + 1
  sequence_index = $index
  position = 10
  num_rows = 8
  num_columns = 12
  well_volume = 0.2
}

arm -r-> tips
tips -r-> waste
waste -r-> water
water -d-> glucose
glucose -l-> phosphate
phosphate -l-> target

@enduml
