@startuml

class Reservoir {
    +int position
    +str description
}

class TargetPlate {
    +int position
    +int num_rows
    +int num_columns
    +float well_volume
    +dict fill_state
    +add_to_well()
    +remove_from_well()
}

class HandlingArm {
    +int position
    +bool is_loaded
    +bool is_clean
    +bool is_lowered
    +load_tips()
    +eject_tips()
    +move()
    +lower()
    +raise()
    +draw_liquid()
    +dispense_liquid()
}

class LiquidHandlingApplication {
    +add_reservoir()
    +remove_reservoir()
    +add_target_plate()
    +remove_target_plate()
    +transfer_liquid()
}
    
LiquidHandlingApplication ..> Reservoir
LiquidHandlingApplication ..> TargetPlate
LiquidHandlingApplication ..> HandlingArm

@enduml